### ISSUE TITLE
🐛 Bug: Resources' favicon not loading

### ISSUE THREAD

**Issue by esau-morais** [floriandwt/Curations#6]
### Problem

It seems like multiple resources are not having its favicon image not being load

![favicon image not being load](https://user-images.githubusercontent.com/55207584/204165247-453639ec-176f-4413-ab48-3b9bbfaee563.png)

![INVALID_IMAGE_OPTIMIZE_REQUEST](https://user-images.githubusercontent.com/55207584/204165358-bd017574-618d-4dbc-8a8d-1b96ef1d717d.png)

**Comment by stallboerger** [comment]
This issue is known to us due to a missing favicon or the favicon of the website being a svg. We already fixed the favicons for those sites and push it on the next deployment.
